<?php

namespace Bakgat\Notos\__CG__\Bakgat\Notos\Domain\Model\Curricula;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Curriculum extends \Bakgat\Notos\Domain\Model\Curricula\Curriculum implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'id', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'course', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'year_published', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'code', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'structures');
        }

        return array('__isInitialized__', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'id', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'course', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'year_published', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'code', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Curricula\\Curriculum' . "\0" . 'structures');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Curriculum $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function id()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::id();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::id();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourse(\Bakgat\Notos\Domain\Model\Curricula\Course $course)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourse', array($course));

        return parent::setCourse($course);
    }

    /**
     * {@inheritDoc}
     */
    public function course()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'course', array());

        return parent::course();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearPublished($yearPublished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearPublished', array($yearPublished));

        return parent::setYearPublished($yearPublished);
    }

    /**
     * {@inheritDoc}
     */
    public function yearPublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'yearPublished', array());

        return parent::yearPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function code()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'code', array());

        return parent::code();
    }

    /**
     * {@inheritDoc}
     */
    public function getStructures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructures', array());

        return parent::getStructures();
    }

    /**
     * {@inheritDoc}
     */
    public function addStructure(\Bakgat\Notos\Domain\Model\Curricula\Structure $structure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStructure', array($structure));

        return parent::addStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStructure(\Bakgat\Notos\Domain\Model\Curricula\Structure $structure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStructure', array($structure));

        return parent::removeStructure($structure);
    }

}
